name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Varun-Tulsiyani
          template: classic
          base: header, activity, community
          base_indepth: yes
          config_timezone: Asia/Dubai

          plugin_lines: yes
          plugin_lines_sections: base, history
          plugin_lines_history_limit: 0

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
