# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Varun-Tulsiyani
          template: classic
          base: topics, metadata
          config_timezone: Asia/Dubai
          filename: metrics_2.svg

          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_limit: 0
          plugin_languages_colors: github
          plugin_languages_sections: most-used
          plugin_languages_details: lines, bytes-size, percentage
          plugin_languages_analysis_timeout: 60
          plugin_languages_categories: markup, programming
          plugin_languages_threshold: 0%

          plugin_followup: yes
          plugin_followup_indepth: yes
          plugins_errors_fatal: yes
